# Generated by Django 4.0.1 on 2022-01-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=255, unique=True)),
                ('amount', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('customerPhoneNumber', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('referenceProduct', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
