# Generated by Django 4.0.1 on 2022-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('transactions', models.CharField(max_length=1000)),
                ('time', models.IntegerField()),
                ('process', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='AirtelMoneyTransaction',
        ),
    ]
